spring:
  application:
    name: Web
  datasource:
    url: jdbc:postgresql://localhost:5432/first_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
    show-sql: true

logging:
  level:

    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE


admin:
  password:
    1

test:
  records:
    count: 13